### ISSUE TITLE
Question: node-driver use to work with a callback in the readTag call. Is this not possible any more?

### ISSUE THREAD

**Issue by gman8a** [jmmoser/node-drivers#6]
Justin,

   Questions
      "node-drivers" use to work with a callback in the read Tag call. 
        Is this not possible any more? 
          I am not sure what "await" does.  Does the **node executive loop** process other functions while waiting ? 
       
      Also, can "node-drivers" talk to a A/B Compact-Logix or Control-Logix PLC ?
       If so, I see no examples of this. Seem like all the necessary low level code is in place for this.

**Comment by jmmoser** [comment]
Can you share the error you receive when you try to use a callback?  You should be able to do something like this without issue:
```javascript
logix5000.readTag('tagname', function(res) {

});
```

Async/await is syntax for writing asynchronous JavaScript and is built on top of promises.  Here are a few links that cover async/await:
- https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await
- https://javascript.info/async-await
- https://www.digitalocean.com/community/tutorials/js-async-functions
The node executive loop (event loop) is single threaded and will only process one function at a time, however, I/O runs on separate threads.  This means you can run one asynchronous function, then run another ansynchronous function, then wait for both of them to finish.  See the code example below:

```javascript
/**
 * test1 requests the value of tag1 and waits for the response,
 * then requests the value of tag2 and waits for the response
 */
async function test1() {
	const promise1 = logix5000.readTag('tag1');
	const value1 = await promise1;

	const promise2 = logix5000.readTag('tag2');  
	const value2 = await promise2;
}

/**
 * test2 requests the value of tag1, then requests the value of tag2,
 * then waits for the response of tag1, then waits for the response of tag2.
 * This may execute faster than test1 because while you are waiting for tag1's response, tag2's
 * value has already been requested.  It doesn't wait for tag1's response before requesting tag1's value.
 */
async function test2() {
	  const promise1 = logix5000.readTag('tag1');
	  const promise2 = logix5000.readTag('tag2');
	  
	  const value1 = await promise1;
	  const value2 = await promise2;
}
```

Use the Logix5000 layer on top of the TCP layer to communicate with Control-Logix and Compact-Logix PLCs.  The code example is [here](https://github.com/jmmoser/node-drivers/blob/master/examples/Logix5000.js).  The documentation I followed for developing the Logix5000 layer is [here](https://github.com/jmmoser/node-drivers/blob/master/documents/CIP%20Logix5000%201756-PM020.pdf).

**Comment by gman8a** [comment]
I guess it it this, as programmed in your example to me.

const callbackStart = Date.now();
	logix5000.readTag('HMI_CC03_FULL[0]', (err, result) => {
		const callbackEnd = Date.now();
		if (err) {
			console.log('Error reading tag using promise', err);
		} else {
			console.log('Time elapsed for callback:', callbackEnd - callbackStart);
		}
		
		tcpLayer.close();
	});

**Comment by gman8a** [comment]
HMI_CC03_FULL[0]
cnt: 7   Error reading tag using promise InfoError: connection.cip error: ConnectionFailure, Connection in use or duplicate forward open
    at Object.reject (/mnt/WIC/wic_handcraft2/plc2/node_modules/node-drivers/src/utils.js:131:19)
    at /mnt/WIC/wic_handcraft2/plc2/node_modules/node-drivers/src/layers/cip/layers/Logix5000/index.js:206:20
    at send (/mnt/WIC/wic_handcraft2/plc2/node_modules/node-drivers/src/layers/cip/layers/Logix5000/index.js:1000:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  info: undefined
}
InfoError: connection.cip error: ConnectionFailure, Connection in use or duplicate forward open
    at Object.reject (/mnt/WIC/wic_handcraft2/plc2/node_modules/node-drivers/src/utils.js:131:19)
    at /mnt/WIC/wic_handcraft2/plc2/node_modules/node-drivers/src/layers/cip/layers/internal/CIPInternalLayer.js:42:22
    at /mnt/WIC/wic_handcraft2/plc2/node_modules/node-drivers/src/layers/Layer.js:275:43
    at Map.forEach (<anonymous>)
    at internalDestroy (/mnt/WIC/wic_handcraft2/plc2/node_modules/node-drivers/src/layers/Layer.js:275:29)
    at Logix5000.destroy (/mnt/WIC/wic_handcraft2/plc2/node_modules/node-drivers/src/layers/Layer.js:117:5)
    at CIPConnectionLayer.destroy (/mnt/WIC/wic_handcraft2/plc2/node_modules/node-drivers/src/layers/Layer.js:114:23)
    at /mnt/WIC/wic_handcraft2/plc2/node_modules/node-drivers/src/layers/cip/layers/internal/CIPConnectionLayer.js:575:18
    at handleUnconnectedMessage (/mnt/WIC/wic_handcraft2/plc2/node_modules/node-drivers/src/layers/cip/layers/internal/CIPConnectionLayer.js:225:7)
    at CIPConnectionLayer.handleData (/mnt/WIC/wic_handcraft2/plc2/node_modules/node-drivers/src/layers/cip/layers/internal/CIPConnectionLayer.js:143:7) {
  info: undefined
}
HMI_CC03_FULL[0]
cnt: 8   Error reading tag using promise InfoError: connection.cip error: ConnectionFailure, Connection in use or duplicate forward open
    at Object.reject (/mnt/WIC/wic_handcraft2/plc2/node_modules/node-drivers/src/utils.js:131:19)
    at /mnt/WIC/wic_handcraft2/plc2/node_modules/node-drivers/src/layers/cip/layers/Logix5000/index.js:206:20
    at send (/mnt/WIC/wic_handcraft2/plc2/node_modules/node-drivers/src/layers/cip/layers/Logix5000/index.js:1000:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  info: undefined
}


^^^^^^^^^^^^^ERROR FROMP REVIOUS RUN ABOVE ^^^^^^^^^^^


Rcv:~/wic/plc2$ node p1.js 
here  1
here  2
here  3
here  4
here  5
here  6
here  7
here  8
cnt: 2   Time elapsed for callback: 86
cnt: 3   Time elapsed for callback: 91
cnt: 4   Time elapsed for callback: 93
cnt: 5   Time elapsed for callback: 96
cnt: 6   Time elapsed for callback: 99
cnt: 7   Time elapsed for callback: 101
cnt: 8   Time elapsed for callback: 103



-------------CODE---------------------
function f1(cnt){
		let callbackStart = Date.now();
		console.log('here ', cnt);

		logix5000.readTag('HMI_CC03_FULL[0]', (err, result) => {

			let callbackEnd = Date.now();

				if (err) {
						console.log('cnt:', cnt,'  Error reading tag using promise', err);
				} else {
						
						console.log('cnt:', cnt, '  Time elapsed for callback:', callbackEnd - callbackStart);
				}
					
		});
}//fn

f1(1)
f1(2);
f1(3);
f1(4);
f1(5);
f1(6);
f1(7);
f1(8);

setTimeout( ()=>{  

	logix5000.close();
	cipLayer.close();
	tcpLayer.close(); 


	process.exit(); 

}, 3000);


-----------END CODE------------------------

**Comment by gman8a** [comment]
///output of your last program request follows

_Rcv:~/wic/plc2$ node p4.js 
here  1
cnt: 1   Time elapsed for callback: 99
here  2
cnt: 2   Time elapsed for callback: 6
here  3
cnt: 3   Time elapsed for callback: 4
here  4
cnt: 4   Time elapsed for callback: 4
here  5
cnt: 5   Time elapsed for callback: 4
here  6
cnt: 6   Time elapsed for callback: 4
here  7
cnt: 7   Time elapsed for callback: 4
here  8
cnt: 8   Time elapsed for callback: 4

/plc2/p4.js:49
    cipLayer.close();
    ^

ReferenceError: cipLayer is not defined
    at Timeout._onTimeout (/mnt/WIC/wic_handcraft2/plc2/p4.js:49:5)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Comment by gman8a** [comment]
...more than it did when i started.

   ..however my application looks like this:
//////////////////////////   
    function readmytag(tagname, (result) => {

              ..
              ..
              ...
             plc_result_data_handler(result);

    });

    readmytag('HMI_CC03_FULL[0]');

//////////////////////

The time from the app call to the handler should be 5ms.
Please code this for me !!
